# QUESTION1 Gas turbine

In [47]:
import pandas as pd
import numpy as np
import sklearn

In [48]:
from google.colab import files
uploaded=files.upload()

Saving gas_turbines.csv to gas_turbines (1).csv

In [49]:
GT=pd.read_csv("gas_turbines.csv")
GT

,AT,AP,AH,AFDP,GTEP,TIT,TAT,TEY,CDP,CO,NOX
0,6.8594,1007.9,96.799,3.5000,19.663,1059.2,550.00,114.70,10.605,3.1547,82.722
1,6.7850,1008.4,97.118,3.4998,19.728,1059.3,550.00,114.72,10.598,3.2363,82.776
2,6.8977,1008.8,95.939,3.4824,19.779,1059.4,549.87,114.71,10.601,3.2012,82.468
3,7.0569,1009.2,95.249,3.4805,19.792,1059.6,549.99,114.72,10.606,3.1923,82.670
4,7.3978,1009.7,95.150,3.4976,19.765,1059.7,549.98,114.72,10.612,3.2484,82.311
...,...,...,...,...,...,...,...,...,...,...,...
15034,9.0301,1005.6,98.460,3.5421,19.164,1049.7,546.21,111.61,10.400,4.5186,79.559
15035,7.8879,1005.9,99.093,3.5059,19.414,1046.3,543.22,111.78,10.433,4.8470,79.917
15036,7.2647,1006.3,99.496,3.4770,19.530,1037.7,537.32,110.19,10.483,7.9632,90.912
15037,7.0060,1006.8,99.008,3.4486,19.377,1043.2,541.24,110.74,10.533,6.2494,93.227
15038,6.9279,1007.2,97.533,3.4275,19.306,1049.9,545.85,111.58,10.583,4.9816,92.498

In [50]:
GT.describe()

,AT,AP,AH,AFDP,GTEP,TIT,TAT,TEY,CDP,CO,NOX
count,15039.000000,15039.00000,15039.000000,15039.000000,15039.000000,15039.000000,15039.000000,15039.000000,15039.000000,15039.000000,15039.000000
mean,17.764381,1013.19924,79.124174,4.200294,25.419061,1083.798770,545.396183,134.188464,12.102353,1.972499,68.190934
std,7.574323,6.41076,13.793439,0.760197,4.173916,16.527806,7.866803,15.829717,1.103196,2.222206,10.470586
min,0.522300,985.85000,30.344000,2.087400,17.878000,1000.800000,512.450000,100.170000,9.904400,0.000388,27.765000
25%,11.408000,1008.90000,69.750000,3.723900,23.294000,1079.600000,542.170000,127.985000,11.622000,0.858055,61.303500
50%,18.186000,1012.80000,82.266000,4.186200,25.082000,1088.700000,549.890000,133.780000,12.025000,1.390200,66.601000
75%,23.862500,1016.90000,90.043500,4.550900,27.184000,1096.000000,550.060000,140.895000,12.578000,2.160400,73.935500
max,34.929000,1034.20000,100.200000,7.610600,37.402000,1100.800000,550.610000,174.610000,15.081000,44.103000,119.890000

In [51]:
GT.shape

(15039, 11)

In [52]:
GT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15039 entries, 0 to 15038
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      15039 non-null  float64
 1   AP      15039 non-null  float64
 2   AH      15039 non-null  float64
 3   AFDP    15039 non-null  float64
 4   GTEP    15039 non-null  float64
 5   TIT     15039 non-null  float64
 6   TAT     15039 non-null  float64
 7   TEY     15039 non-null  float64
 8   CDP     15039 non-null  float64
 9   CO      15039 non-null  float64
 10  NOX     15039 non-null  float64
dtypes: float64(11)
memory usage: 1.3 MB

In [53]:
GT.columns

Index(['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'TEY', 'CDP', 'CO',
       'NOX'],
      dtype='object')

In [54]:
GT.isnull().sum()

AT      0
AP      0
AH      0
AFDP    0
GTEP    0
TIT     0
TAT     0
TEY     0
CDP     0
CO      0
NOX     0
dtype: int64

In [55]:
# check for duplicate data
duplicate = GT.duplicated()
print(duplicate.sum())
GT[duplicate]

0

Empty DataFrame
Columns: [AT, AP, AH, AFDP, GTEP, TIT, TAT, TEY, CDP, CO, NOX]
Index: []

In [56]:
X = GT.loc[:,['AT', 'AP', 'AH', 'AFDP', 'GTEP', 'TIT', 'TAT', 'CDP', 'CO','NOX']]
y= GT.loc[:,['TEY']]

In [57]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
scaler = StandardScaler()
X = scaler.fit_transform(X)
y = scaler.fit_transform(y)

In [58]:
def baseline_model():
    model = Sequential()
    model.add(Dense(10, input_dim=10, activation='tanh'))
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [59]:

import keras
from sklearn.model_selection import KFold
from keras.wrappers.scikit_learn import KerasRegressor
from keras.models import Sequential
from keras.layers import InputLayer,Dense
estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=50, batch_size=100, verbose=False)
kfold = KFold(n_splits=10)
results = cross_val_score(estimator, X, y, cv=kfold)
print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

<ipython-input-59-ae62adc6907d>:6: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=50, batch_size=100, verbose=False)

Results: -0.17 (0.15) MSE

In [60]:
estimator.fit(X, y)
prediction = estimator.predict(X)
prediction

array([-1.1797549, -1.1919717, -1.2080468, ..., -2.0134175, -1.9221991,
       -1.6744384], dtype=float32)

In [61]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
y_train.shape

(10527, 10)

In [62]:
estimator.fit(X_train, y_train)
prediction = estimator.predict(X_test)

In [63]:
prediction

array([ 0.13491237,  0.14321859,  0.32959318, ..., -0.08752802,
        0.22956824, -0.05425438], dtype=float32)

In [64]:
X = GT.drop(columns = ['TEY'], axis = 1) 
y = GT.iloc[:,7]

In [65]:
from sklearn.preprocessing import scale
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)
X_train_scaled = scale(X_train)
X_test_scaled = scale(X_test)
X_test_scaled

array([[ 0.82623246, -0.43954308, -0.25924569, ...,  0.10039242,
        -0.3796304 , -0.69217007],
       [ 0.35282087,  0.23279782,  0.80230139, ..., -1.18541222,
         0.39149515, -1.09475442],
       [ 0.32839008, -0.07135639,  0.25312287, ...,  0.01665304,
        -0.00296896, -0.31891741],
       ...,
       [-0.74071701,  0.37687087,  0.43427425, ...,  1.77157829,
        -1.00127821, -0.4818816 ],
       [-0.49965786, -0.39151873,  0.64680105, ..., -0.26517949,
        -0.48137538,  0.12808615],
       [ 0.13151427,  0.32884652,  0.98830762, ..., -1.40331469,
         0.13152215, -0.64456466]])

In [66]:
import tensorflow as tf
input_size = len(X.columns)
output_size = 1
hidden_layer_size = 50

model = tf.keras.Sequential([
                                
                               tf.keras.layers.Dense(hidden_layer_size, input_dim = input_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
                               tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),     
                               tf.keras.layers.Dense(output_size)
                             ])

In [67]:
optimizer = tf.keras.optimizers.SGD(learning_rate = 0.03)
model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['MeanSquaredError'])

In [68]:

num_epochs = 100
early_stopping=tf.keras.callbacks.EarlyStopping(patience = 2) 
model.fit(X_train_scaled, y_train,callbacks = early_stopping, validation_split = 0.1, epochs = num_epochs, verbose = 2)

Epoch 1/100
381/381 - 1s - loss: 2726.6228 - mean_squared_error: 2726.6228 - val_loss: 201.5285 - val_mean_squared_error: 201.5285 - 1s/epoch - 3ms/step
Epoch 2/100
381/381 - 0s - loss: 108.7275 - mean_squared_error: 108.7275 - val_loss: 78.7954 - val_mean_squared_error: 78.7954 - 460ms/epoch - 1ms/step
Epoch 3/100
381/381 - 1s - loss: 47.2135 - mean_squared_error: 47.2135 - val_loss: 40.1722 - val_mean_squared_error: 40.1722 - 509ms/epoch - 1ms/step
Epoch 4/100
381/381 - 0s - loss: 25.7371 - mean_squared_error: 25.7371 - val_loss: 22.3713 - val_mean_squared_error: 22.3713 - 473ms/epoch - 1ms/step
Epoch 5/100
381/381 - 0s - loss: 14.9109 - mean_squared_error: 14.9109 - val_loss: 13.4457 - val_mean_squared_error: 13.4457 - 489ms/epoch - 1ms/step
Epoch 6/100
381/381 - 0s - loss: 8.1833 - mean_squared_error: 8.1833 - val_loss: 7.1667 - val_mean_squared_error: 7.1667 - 491ms/epoch - 1ms/step
Epoch 7/100
381/381 - 0s - loss: 4.8756 - mean_squared_error: 4.8756 - val_loss: 3.3953 - val_mean_squared_error: 3.3953 - 459ms/epoch - 1ms/step
Epoch 8/100
381/381 - 0s - loss: 2.8526 - mean_squared_error: 2.8526 - val_loss: 2.7730 - val_mean_squared_error: 2.7730 - 444ms/epoch - 1ms/step
Epoch 9/100
381/381 - 0s - loss: 1.9447 - mean_squared_error: 1.9447 - val_loss: 2.1914 - val_mean_squared_error: 2.1914 - 470ms/epoch - 1ms/step
Epoch 10/100
381/381 - 1s - loss: 1.5002 - mean_squared_error: 1.5002 - val_loss: 1.2485 - val_mean_squared_error: 1.2485 - 672ms/epoch - 2ms/step
Epoch 11/100
381/381 - 1s - loss: 1.2839 - mean_squared_error: 1.2839 - val_loss: 0.9812 - val_mean_squared_error: 0.9812 - 652ms/epoch - 2ms/step
Epoch 12/100
381/381 - 1s - loss: 1.1131 - mean_squared_error: 1.1131 - val_loss: 1.3011 - val_mean_squared_error: 1.3011 - 754ms/epoch - 2ms/step
Epoch 13/100
381/381 - 1s - loss: 0.9694 - mean_squared_error: 0.9694 - val_loss: 1.3316 - val_mean_squared_error: 1.3316 - 754ms/epoch - 2ms/step

In [69]:

test_loss, mean_squared_error = model.evaluate(X_test_scaled, y_test)

47/47 [==============================] - 0s 1ms/step - loss: 1.1236 - mean_squared_error: 1.1236

In [70]:
predictions = model.predict_on_batch(X_test_scaled)
predictions

array([[135.5542  ],
       [113.304955],
       [134.47568 ],
       ...,
       [160.80907 ],
       [133.84612 ],
       [112.71492 ]], dtype=float32)

In [71]:
predictions_df = pd.DataFrame()
predictions_df['Actual'] = y_test
predictions_df['Predicted'] = predictions
predictions_df['% Error'] = abs(predictions_df['Actual'] - predictions_df['Predicted'])/predictions_df['Actual']*100
predictions_df.reset_index(drop = True)

      Actual   Predicted   % Error
0     134.46  135.554199  0.813773
1     111.88  113.304955  1.273645
2     133.72  134.475677  0.565119
3     133.79  134.451874  0.494711
4     110.77  112.249512  1.335661
...      ...         ...       ...
1499  132.85  133.852753  0.754801
1500  125.07  123.283173  1.428662
1501  160.95  160.809067  0.087563
1502  133.12  133.846115  0.545459
1503  111.79  112.714920  0.827373

[1504 rows x 3 columns]

# Q2 FOREST FIRES

In [72]:
import pandas as pd
import numpy as np
import sklearn

In [73]:
from google.colab import files
uploaded=files.upload()

Saving forestfires.csv to forestfires (1).csv

In [74]:
FF=pd.read_csv("forestfires.csv")
FF

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,...,0,0,0,0,0,0,0,0,0,large
513,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,...,0,0,0,0,0,0,0,0,0,large
514,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,...,0,0,0,0,0,0,0,0,0,large
515,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,...,0,0,0,0,0,0,0,0,0,small
516,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,...,0,0,0,0,0,0,1,0,0,small

In [75]:

ff1=FF.drop(['month','day'],axis=1)

In [76]:
ff1['size_category'].value_counts()

small    378
large    139
Name: size_category, dtype: int64

In [77]:
ff1.isnull().sum()

FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [78]:
ff1.describe()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,...,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,12.847292,0.164410,...,0.017408,0.038685,0.003868,0.061896,0.032882,0.104449,0.003868,0.001934,0.029014,0.332689
std,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,63.655818,0.371006,...,0.130913,0.193029,0.062137,0.241199,0.178500,0.306138,0.062137,0.043980,0.168007,0.471632
min,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,0.520000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,6.570000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,1090.840000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [79]:
ff1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FFMC           517 non-null    float64
 1   DMC            517 non-null    float64
 2   DC             517 non-null    float64
 3   ISI            517 non-null    float64
 4   temp           517 non-null    float64
 5   RH             517 non-null    int64
 6   wind           517 non-null    float64
 7   rain           517 non-null    float64
 8   area           517 non-null    float64
 9   dayfri         517 non-null    int64
 10  daymon         517 non-null    int64
 11  daysat         517 non-null    int64
 12  daysun         517 non-null    int64
 13  daythu         517 non-null    int64
 14  daytue         517 non-null    int64
 15  daywed         517 non-null    int64
 16  monthapr       517 non-null    int64
 17  monthaug       517 non-null    int64
 18  monthdec       517 non-null    int64
 19  monthfeb       517 non-null    int64
 20  monthjan       517 non-null    int64
 21  monthjul       517 non-null    int64
 22  monthjun       517 non-null    int64
 23  monthmar       517 non-null    int64
 24  monthmay       517 non-null    int64
 25  monthnov       517 non-null    int64
 26  monthoct       517 non-null    int64
 27  monthsep       517 non-null    int64
 28  size_category  517 non-null    object
dtypes: float64(8), int64(20), object(1)
memory usage: 117.3+ KB

In [80]:
ff1['size_category'].unique()

array(['small', 'large'], dtype=object)

In [81]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows 
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
ff1['size_category']= label_encoder.fit_transform(ff1['size_category'])
  
ff1['size_category'].unique()

array([1, 0])

In [82]:
ff1

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,1,...,0,0,0,0,1,0,0,0,0,1
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,0,...,0,0,0,0,0,0,0,1,0,1
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,0,...,0,0,0,0,0,0,0,1,0,1
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,1,...,0,0,0,0,1,0,0,0,0,1
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,0,...,0,0,0,0,0,0,0,0,0,0
513,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,0,...,0,0,0,0,0,0,0,0,0,0
514,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,0,...,0,0,0,0,0,0,0,0,0,0
515,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,0,...,0,0,0,0,0,0,0,0,0,1
516,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,0,...,0,0,0,0,0,0,1,0,0,1

In [83]:
x = np.array(ff1.iloc[:,0:28])
y = np.array(ff1.iloc[:,28])

In [84]:
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [85]:
x_norm = norm_func(x)

In [86]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x_norm,y, test_size=0.2,stratify = y)

In [121]:
from tensorflow import keras
from keras.layers import Dense
from keras.models import Sequential, load_model
model = Sequential()
model.add(Dense(8, input_dim=28, activation='linear'))
model.add(Dense(4,  activation='tanh'))
model.add(Dense(1,  activation='sigmoid'))

In [129]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

In [135]:
train_loss, train_acc = model.evaluate(x_train, y_train, verbose=2)
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)

13/13 - 0s - loss: 0.0511 - accuracy: 0.9879 - 28ms/epoch - 2ms/step
4/4 - 0s - loss: 0.0729 - accuracy: 0.9808 - 19ms/epoch - 5ms/step

In [132]:
test_loss_2, mean_squared_error_2 = model.fit(x_train, y_train, validation_split=0.3, epochs=120, batch_size=20)

Epoch 1/120
15/15 [==============================] - 0s 6ms/step - loss: 0.1275 - accuracy: 0.9516 - val_loss: 0.1268 - val_accuracy: 0.9677
Epoch 2/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1273 - accuracy: 0.9619 - val_loss: 0.1281 - val_accuracy: 0.9677
Epoch 3/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1250 - accuracy: 0.9654 - val_loss: 0.1222 - val_accuracy: 0.9677
Epoch 4/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1250 - accuracy: 0.9689 - val_loss: 0.1210 - val_accuracy: 0.9677
Epoch 5/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1217 - accuracy: 0.9550 - val_loss: 0.1213 - val_accuracy: 0.9677
Epoch 6/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1217 - accuracy: 0.9723 - val_loss: 0.1189 - val_accuracy: 0.9597
Epoch 7/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1209 - accuracy: 0.9550 - val_loss: 0.1263 - val_accuracy: 0.9677
Epoch 8/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1246 - accuracy: 0.9550 - val_loss: 0.1208 - val_accuracy: 0.9677
Epoch 9/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1179 - accuracy: 0.9792 - val_loss: 0.1187 - val_accuracy: 0.9677
Epoch 10/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1157 - accuracy: 0.9619 - val_loss: 0.1181 - val_accuracy: 0.9677
Epoch 11/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1148 - accuracy: 0.9654 - val_loss: 0.1191 - val_accuracy: 0.9677
Epoch 12/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1130 - accuracy: 0.9758 - val_loss: 0.1149 - val_accuracy: 0.9677
Epoch 13/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1115 - accuracy: 0.9689 - val_loss: 0.1150 - val_accuracy: 0.9677
Epoch 14/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1102 - accuracy: 0.9758 - val_loss: 0.1168 - val_accuracy: 0.9677
Epoch 15/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1119 - accuracy: 0.9689 - val_loss: 0.1119 - val_accuracy: 0.9677
Epoch 16/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1099 - accuracy: 0.9862 - val_loss: 0.1119 - val_accuracy: 0.9677
Epoch 17/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1092 - accuracy: 0.9585 - val_loss: 0.1115 - val_accuracy: 0.9677
Epoch 18/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1082 - accuracy: 0.9862 - val_loss: 0.1089 - val_accuracy: 0.9677
Epoch 19/120
15/15 [==============================] - 0s 3ms/step - loss: 0.1113 - accuracy: 0.9585 - val_loss: 0.1171 - val_accuracy: 0.9677
Epoch 20/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1084 - accuracy: 0.9792 - val_loss: 0.1074 - val_accuracy: 0.9677
Epoch 21/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1035 - accuracy: 0.9689 - val_loss: 0.1107 - val_accuracy: 0.9758
Epoch 22/120
15/15 [==============================] - 0s 5ms/step - loss: 0.1023 - accuracy: 0.9723 - val_loss: 0.1064 - val_accuracy: 0.9677
Epoch 23/120
15/15 [==============================] - 0s 5ms/step - loss: 0.1020 - accuracy: 0.9758 - val_loss: 0.1082 - val_accuracy: 0.9758
Epoch 24/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1018 - accuracy: 0.9689 - val_loss: 0.1070 - val_accuracy: 0.9677
Epoch 25/120
15/15 [==============================] - 0s 4ms/step - loss: 0.1004 - accuracy: 0.9896 - val_loss: 0.1048 - val_accuracy: 0.9677
Epoch 26/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0980 - accuracy: 0.9758 - val_loss: 0.1048 - val_accuracy: 0.9677
Epoch 27/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0972 - accuracy: 0.9723 - val_loss: 0.1055 - val_accuracy: 0.9839
Epoch 28/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0975 - accuracy: 0.9792 - val_loss: 0.1017 - val_accuracy: 0.9677
Epoch 29/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0968 - accuracy: 0.9792 - val_loss: 0.1019 - val_accuracy: 0.9677
Epoch 30/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0946 - accuracy: 0.9792 - val_loss: 0.1021 - val_accuracy: 0.9758
Epoch 31/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0932 - accuracy: 0.9792 - val_loss: 0.0999 - val_accuracy: 0.9677
Epoch 32/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0923 - accuracy: 0.9758 - val_loss: 0.1007 - val_accuracy: 0.9758
Epoch 33/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0916 - accuracy: 0.9896 - val_loss: 0.0996 - val_accuracy: 0.9758
Epoch 34/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0923 - accuracy: 0.9723 - val_loss: 0.0997 - val_accuracy: 0.9758
Epoch 35/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0903 - accuracy: 0.9862 - val_loss: 0.0975 - val_accuracy: 0.9677
Epoch 36/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0913 - accuracy: 0.9723 - val_loss: 0.0996 - val_accuracy: 0.9677
Epoch 37/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0888 - accuracy: 0.9792 - val_loss: 0.0976 - val_accuracy: 0.9839
Epoch 38/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0871 - accuracy: 0.9862 - val_loss: 0.0994 - val_accuracy: 0.9677
Epoch 39/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0867 - accuracy: 0.9862 - val_loss: 0.0948 - val_accuracy: 0.9677
Epoch 40/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0867 - accuracy: 0.9758 - val_loss: 0.0988 - val_accuracy: 0.9677
Epoch 41/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0866 - accuracy: 0.9827 - val_loss: 0.0949 - val_accuracy: 0.9839
Epoch 42/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0850 - accuracy: 0.9896 - val_loss: 0.0929 - val_accuracy: 0.9677
Epoch 43/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0867 - accuracy: 0.9689 - val_loss: 0.0962 - val_accuracy: 0.9677
Epoch 44/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0847 - accuracy: 0.9792 - val_loss: 0.0955 - val_accuracy: 0.9677
Epoch 45/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0827 - accuracy: 0.9827 - val_loss: 0.0952 - val_accuracy: 0.9677
Epoch 46/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0823 - accuracy: 0.9896 - val_loss: 0.0910 - val_accuracy: 0.9677
Epoch 47/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0828 - accuracy: 0.9827 - val_loss: 0.0930 - val_accuracy: 0.9677
Epoch 48/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0837 - accuracy: 0.9723 - val_loss: 0.0939 - val_accuracy: 0.9677
Epoch 49/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0799 - accuracy: 0.9862 - val_loss: 0.0916 - val_accuracy: 0.9677
Epoch 50/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0789 - accuracy: 0.9792 - val_loss: 0.0887 - val_accuracy: 0.9677
Epoch 51/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0781 - accuracy: 0.9792 - val_loss: 0.0910 - val_accuracy: 0.9677
Epoch 52/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0773 - accuracy: 0.9931 - val_loss: 0.0884 - val_accuracy: 0.9839
Epoch 53/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0758 - accuracy: 0.9896 - val_loss: 0.0885 - val_accuracy: 0.9758
Epoch 54/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0762 - accuracy: 0.9931 - val_loss: 0.0865 - val_accuracy: 0.9677
Epoch 55/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0784 - accuracy: 0.9689 - val_loss: 0.0888 - val_accuracy: 0.9677
Epoch 56/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0753 - accuracy: 0.9896 - val_loss: 0.0862 - val_accuracy: 0.9839
Epoch 57/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0739 - accuracy: 0.9758 - val_loss: 0.0867 - val_accuracy: 0.9677
Epoch 58/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0731 - accuracy: 1.0000 - val_loss: 0.0854 - val_accuracy: 0.9758
Epoch 59/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0733 - accuracy: 0.9862 - val_loss: 0.0854 - val_accuracy: 0.9677
Epoch 60/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0741 - accuracy: 0.9792 - val_loss: 0.0894 - val_accuracy: 0.9677
Epoch 61/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0730 - accuracy: 0.9931 - val_loss: 0.0838 - val_accuracy: 0.9839
Epoch 62/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0703 - accuracy: 0.9862 - val_loss: 0.0866 - val_accuracy: 0.9677
Epoch 63/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0707 - accuracy: 0.9827 - val_loss: 0.0846 - val_accuracy: 0.9677
Epoch 64/120
15/15 [==============================] - 0s 6ms/step - loss: 0.0704 - accuracy: 0.9896 - val_loss: 0.0839 - val_accuracy: 0.9677
Epoch 65/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0689 - accuracy: 0.9931 - val_loss: 0.0836 - val_accuracy: 0.9677
Epoch 66/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0681 - accuracy: 0.9862 - val_loss: 0.0819 - val_accuracy: 0.9839
Epoch 67/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0675 - accuracy: 0.9862 - val_loss: 0.0826 - val_accuracy: 0.9677
Epoch 68/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0673 - accuracy: 0.9862 - val_loss: 0.0882 - val_accuracy: 0.9677
Epoch 69/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0685 - accuracy: 0.9862 - val_loss: 0.0804 - val_accuracy: 0.9758
Epoch 70/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0682 - accuracy: 0.9896 - val_loss: 0.0799 - val_accuracy: 0.9839
Epoch 71/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0666 - accuracy: 0.9827 - val_loss: 0.0820 - val_accuracy: 0.9677
Epoch 72/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0643 - accuracy: 0.9931 - val_loss: 0.0801 - val_accuracy: 0.9677
Epoch 73/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0646 - accuracy: 0.9862 - val_loss: 0.0820 - val_accuracy: 0.9677
Epoch 74/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0650 - accuracy: 0.9965 - val_loss: 0.0782 - val_accuracy: 0.9839
Epoch 75/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0659 - accuracy: 0.9931 - val_loss: 0.0787 - val_accuracy: 0.9758
Epoch 76/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0633 - accuracy: 0.9931 - val_loss: 0.0783 - val_accuracy: 0.9677
Epoch 77/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0625 - accuracy: 0.9896 - val_loss: 0.0801 - val_accuracy: 0.9677
Epoch 78/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0638 - accuracy: 0.9862 - val_loss: 0.0818 - val_accuracy: 0.9677
Epoch 79/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0625 - accuracy: 0.9896 - val_loss: 0.0768 - val_accuracy: 0.9677
Epoch 80/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0630 - accuracy: 0.9896 - val_loss: 0.0761 - val_accuracy: 0.9758
Epoch 81/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0631 - accuracy: 0.9896 - val_loss: 0.0770 - val_accuracy: 0.9677
Epoch 82/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0597 - accuracy: 0.9862 - val_loss: 0.0755 - val_accuracy: 0.9758
Epoch 83/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0612 - accuracy: 0.9931 - val_loss: 0.0751 - val_accuracy: 0.9839
Epoch 84/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0612 - accuracy: 0.9862 - val_loss: 0.0767 - val_accuracy: 0.9677
Epoch 85/120
15/15 [==============================] - 0s 5ms/step - loss: 0.0577 - accuracy: 0.9965 - val_loss: 0.0756 - val_accuracy: 0.9677
Epoch 86/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0589 - accuracy: 0.9862 - val_loss: 0.0764 - val_accuracy: 0.9677
Epoch 87/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0574 - accuracy: 0.9896 - val_loss: 0.0746 - val_accuracy: 0.9677
Epoch 88/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0580 - accuracy: 0.9896 - val_loss: 0.0760 - val_accuracy: 0.9677
Epoch 89/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0571 - accuracy: 0.9965 - val_loss: 0.0749 - val_accuracy: 0.9677
Epoch 90/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0584 - accuracy: 0.9931 - val_loss: 0.0728 - val_accuracy: 0.9758
Epoch 91/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0554 - accuracy: 0.9862 - val_loss: 0.0760 - val_accuracy: 0.9677
Epoch 92/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0554 - accuracy: 0.9896 - val_loss: 0.0730 - val_accuracy: 0.9677
Epoch 93/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0549 - accuracy: 0.9965 - val_loss: 0.0721 - val_accuracy: 0.9677
Epoch 94/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0546 - accuracy: 0.9896 - val_loss: 0.0739 - val_accuracy: 0.9677
Epoch 95/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0545 - accuracy: 0.9896 - val_loss: 0.0748 - val_accuracy: 0.9677
Epoch 96/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0545 - accuracy: 0.9965 - val_loss: 0.0719 - val_accuracy: 0.9677
Epoch 97/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0532 - accuracy: 0.9896 - val_loss: 0.0731 - val_accuracy: 0.9677
Epoch 98/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0539 - accuracy: 0.9965 - val_loss: 0.0715 - val_accuracy: 0.9677
Epoch 99/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0527 - accuracy: 0.9931 - val_loss: 0.0728 - val_accuracy: 0.9677
Epoch 100/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0528 - accuracy: 0.9965 - val_loss: 0.0707 - val_accuracy: 0.9677
Epoch 101/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0515 - accuracy: 0.9896 - val_loss: 0.0723 - val_accuracy: 0.9677
Epoch 102/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0520 - accuracy: 0.9965 - val_loss: 0.0694 - val_accuracy: 0.9758
Epoch 103/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0543 - accuracy: 0.9862 - val_loss: 0.0695 - val_accuracy: 0.9677
Epoch 104/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0509 - accuracy: 0.9931 - val_loss: 0.0737 - val_accuracy: 0.9758
Epoch 105/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0509 - accuracy: 0.9965 - val_loss: 0.0688 - val_accuracy: 0.9677
Epoch 106/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0505 - accuracy: 0.9965 - val_loss: 0.0688 - val_accuracy: 0.9677
Epoch 107/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0495 - accuracy: 0.9931 - val_loss: 0.0709 - val_accuracy: 0.9677
Epoch 108/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0500 - accuracy: 0.9931 - val_loss: 0.0700 - val_accuracy: 0.9677
Epoch 109/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0496 - accuracy: 0.9862 - val_loss: 0.0695 - val_accuracy: 0.9677
Epoch 110/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0485 - accuracy: 0.9965 - val_loss: 0.0678 - val_accuracy: 0.9677
Epoch 111/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0483 - accuracy: 0.9931 - val_loss: 0.0675 - val_accuracy: 0.9677
Epoch 112/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0526 - accuracy: 0.9862 - val_loss: 0.0789 - val_accuracy: 0.9677
Epoch 113/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0553 - accuracy: 0.9965 - val_loss: 0.0689 - val_accuracy: 0.9758
Epoch 114/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0526 - accuracy: 0.9862 - val_loss: 0.0664 - val_accuracy: 0.9677
Epoch 115/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0493 - accuracy: 0.9896 - val_loss: 0.0685 - val_accuracy: 0.9677
Epoch 116/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0473 - accuracy: 0.9931 - val_loss: 0.0666 - val_accuracy: 0.9677
Epoch 117/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0493 - accuracy: 0.9896 - val_loss: 0.0657 - val_accuracy: 0.9839
Epoch 118/120
15/15 [==============================] - 0s 4ms/step - loss: 0.0528 - accuracy: 0.9862 - val_loss: 0.0819 - val_accuracy: 0.9677
Epoch 119/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0509 - accuracy: 0.9931 - val_loss: 0.0660 - val_accuracy: 0.9677
Epoch 120/120
15/15 [==============================] - 0s 3ms/step - loss: 0.0486 - accuracy: 0.9931 - val_loss: 0.0665 - val_accuracy: 0.9677

TypeError: ignored

In [133]:
 _,accuracy = model.evaluate(x_train, y_train)
print('Accuracy: %.2f' % (accuracy*100))

13/13 [==============================] - 0s 1ms/step - loss: 0.0511 - accuracy: 0.9879
Accuracy: 98.79

In [134]:
scores = model.evaluate(x_test, y_test)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

4/4 [==============================] - 0s 2ms/step - loss: 0.0729 - accuracy: 0.9808
accuracy: 98.08%